services:
  - type: web
    name: bosera
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: NODE_ENV
        value: production

  - type: cron
    name: keep-alive
    schedule: "*/10 * * * *"
    env: node
    buildCommand: npm install
    startCommand: node server/keepalive.js
    envVars:
      - key: PING_URL
        sync: false

